import type { Driver, Ride } from './types';

export const initialDrivers: Driver[] = [
  { id: 'driver-1', name: 'John Doe', vehicle: 'Toyota Prius - ABC-123', rating: 4.8, status: 'available', location: { x: 20, y: 30 } },
  { id: 'driver-2', name: 'Jane Smith', vehicle: 'Honda Civic - XYZ-789', rating: 4.9, status: 'available', location: { x: 80, y: 75 } },
  { id: 'driver-3', name: 'Mike Johnson', vehicle: 'Ford Fusion - FGH-456', rating: 4.7, status: 'on-ride', location: { x: 50, y: 50 } },
  { id: 'driver-4', name: 'Sarah Williams', vehicle: 'Chevy Malibu - CDE-321', rating: 4.6, status: 'offline', location: { x: 10, y: 90 } },
  { id: 'driver-5', name: 'Chris Brown', vehicle: 'Nissan Altima - NAB-654', rating: 4.9, status: 'available', location: { x: 65, y: 15 } },
];

export const initialRides: Ride[] = [
  {
    id: 'ride-1',
    passengerPhone: '555-0101',
    pickup: { name: '123 Main St', coords: { x: 25, y: 40 } },
    dropoff: { name: '789 Oak Ave', coords: { x: 70, y: 60 } },
    status: 'pending',
    driverId: null,
    requestTime: new Date(Date.now() - 5 * 60 * 1000),
    isNew: true,
    passengerCount: 1,
    movingFee: false,
  },
  {
    id: 'ride-2',
    passengerPhone: '555-0102',
    pickup: { name: '456 Pine St', coords: { x: 85, y: 80 } },
    dropoff: { name: '101 Maple Dr', coords: { x: 40, y: 20 } },
    status: 'pending',
    driverId: null,
    requestTime: new Date(Date.now() - 2 * 60 * 1000),
    isNew: true,
    passengerCount: 2,
    movingFee: false,
  },
  {
    id: 'ride-3',
    passengerPhone: '555-0103',
    pickup: { name: '212 Elm St', coords: { x: 55, y: 55 } },
    dropoff: { name: '333 Birch Rd', coords: { x: 45, y: 45 } },
    status: 'assigned',
    driverId: 'driver-3',
    requestTime: new Date(Date.now() - 10 * 60 * 1000),
    passengerCount: 1,
    movingFee: true,
  },
    {
    id: 'ride-4',
    passengerPhone: '555-0104',
    pickup: { name: 'Themyscira', coords: { x: 15, y: 15 } },
    dropoff: { name: 'Hall of Justice', coords: { x: 90, y: 90 } },
    status: 'in-progress',
    driverId: 'driver-3',
    requestTime: new Date(Date.now() - 15 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
  },
  {
    id: 'ride-5',
    passengerPhone: '555-0105',
    pickup: { name: 'Wayne Manor', coords: { x: 5, y: 5 } },
    dropoff: { name: 'Wayne Tower', coords: { x: 95, y: 5 } },
    status: 'completed',
    driverId: 'driver-1',
    requestTime: new Date(Date.now() - 60 * 60 * 1000),
    completionTime: new Date(Date.now() - 40 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    fare: 75.50,
    paymentMethod: 'card',
    cardFee: 1,
  },
  {
    id: 'ride-6',
    passengerPhone: '555-0106',
    pickup: { name: 'Daily Planet', coords: { x: 50, y: 80 } },
    dropoff: { name: 'Fortress of Solitude', coords: { x: 0, y: 100 } },
    status: 'cancelled',
    driverId: null,
    requestTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    completionTime: new Date(Date.now() - 110 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
  },
];
