
import type { Ride, Driver } from './types';

export const initialDrivers: Driver[] = [
  { id: 'driver-1', name: 'John Doe', vehicle: 'Toyota Prius - ABC-123', rating: 4.8, status: 'available', location: { x: 20, y: 30 } },
  { id: 'driver-2', name: 'Jane Smith', vehicle: 'Honda Civic - XYZ-789', rating: 4.9, status: 'available', location: { x: 80, y: 75 } },
  { id: 'driver-3', name: 'Mike Johnson', vehicle: 'Ford Fusion - FGH-456', rating: 4.7, status: 'on-ride', location: { x: 50, y: 50 } },
  { id: 'driver-4', name: 'Sarah Williams', vehicle: 'Chevy Malibu - CDE-321', rating: 4.6, status: 'on-ride', location: { x: 10, y: 90 } },
  { id: 'driver-5', name: 'Chris Brown', vehicle: 'Nissan Altima - NAB-654', rating: 4.9, status: 'available', location: { x: 65, y: 15 } },
  { id: 'driver-6', name: 'Emily White', vehicle: 'Tesla Model 3 - TES-654', rating: 5.0, status: 'offline', location: { x: 95, y: 5 } },
  { id: 'driver-7', name: 'David Green', vehicle: 'Subaru Outback - SUB-987', rating: 4.8, status: 'on-ride', location: { x: 40, y: 60 } },
];

const now = new Date();

export const initialRides: Ride[] = [
  // --- Pending Rides (15) ---
  {
    id: 'ride-1',
    passengerPhone: '555-0101',
    pickup: { name: '123 Main St, Cityville', coords: { x: 25, y: 40 } },
    dropoff: { name: '789 Oak Ave, Townburg', coords: { x: 70, y: 60 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 1 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 1 * 60 * 1000),
    isNew: true,
    passengerCount: 1,
    movingFee: false,
    totalFare: 25,
    notes: 'Passenger has a small dog.',
  },
  {
    id: 'ride-2',
    passengerPhone: '555-0102',
    pickup: { name: '456 Pine St, Metropolis', coords: { x: 85, y: 80 } },
    dropoff: { name: '101 Maple Dr, Gotham', coords: { x: 40, y: 20 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 2 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 2 * 60 * 1000),
    isNew: true,
    passengerCount: 2,
    movingFee: false,
    totalFare: 30,
  },
  {
    id: 'ride-3',
    passengerPhone: '555-0103',
    pickup: { name: '212 Elm St, Lakeside', coords: { x: 15, y: 65 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 3 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 3 * 60 * 1000),
    passengerCount: 4,
    movingFee: false,
    totalFare: 18,
  },
  {
    id: 'ride-4',
    passengerPhone: '555-0104',
    pickup: { name: 'Convention Center', coords: { x: 50, y: 25 } },
    dropoff: { name: 'Grand Hotel', coords: { x: 55, y: 35 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 4 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 4 * 60 * 1000),
    passengerCount: 1,
    movingFee: true,
    totalFare: 22,
    notes: 'Lots of luggage.'
  },
  {
    id: 'ride-5',
    passengerPhone: '555-0105',
    pickup: { name: 'Southside Apartments', coords: { x: 70, y: 90 } },
    dropoff: { name: 'Downtown Hospital', coords: { x: 45, y: 40 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 5 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 5 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 28,
  },
    {
    id: 'ride-6',
    passengerPhone: '555-0106',
    pickup: { name: 'Westfield Mall', coords: { x: 10, y: 20 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 6 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 6 * 60 * 1000),
    passengerCount: 3,
    movingFee: false,
    totalFare: 15,
  },
  {
    id: 'ride-7',
    passengerPhone: '555-0107',
    pickup: { name: 'North Beach', coords: { x: 5, y: 5 } },
    dropoff: { name: 'The Pier', coords: { x: 8, y: 12 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 7 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 7 * 60 * 1000),
    passengerCount: 2,
    movingFee: false,
    totalFare: 12,
  },
  {
    id: 'ride-8',
    passengerPhone: '555-0108',
    pickup: { name: 'University Campus', coords: { x: 95, y: 60 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 8 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 8 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 16,
  },
  {
    id: 'ride-9',
    passengerPhone: '555-0109',
    pickup: { name: 'Airport Terminal B', coords: { x: 80, y: 5 } },
    dropoff: { name: 'Marriott Hotel', coords: { x: 60, y: 20 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 9 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 9 * 60 * 1000),
    passengerCount: 2,
    movingFee: false,
    totalFare: 40,
    scheduledTime: new Date(now.getTime() + 60 * 60 * 1000),
    notes: 'Scheduled pickup.'
  },
  {
    id: 'ride-10',
    passengerPhone: '555-0110',
    pickup: { name: 'Old Town', coords: { x: 30, y: 75 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 10 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 10 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 13,
  },
  {
    id: 'ride-11',
    passengerPhone: '555-0111',
    pickup: { name: 'Central Station', coords: { x: 50, y: 50 } },
    dropoff: { name: 'Art Museum', coords: { x: 60, y: 55 } },
    stops: [{ name: 'City Hall', coords: { x: 52, y: 52 } }],
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 11 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 11 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 19,
  },
  {
    id: 'ride-12',
    passengerPhone: '555-0112',
    pickup: { name: 'Eastwood Heights', coords: { x: 90, y: 95 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 12 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 12 * 60 * 1000),
    passengerCount: 5,
    movingFee: false,
    totalFare: 35,
  },
  {
    id: 'ride-13',
    passengerPhone: '555-0113',
    pickup: { name: 'Tech Park', coords: { x: 75, y: 45 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 13 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 13 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 14,
  },
  {
    id: 'ride-14',
    passengerPhone: '555-0114',
    pickup: { name: 'Public Library', coords: { x: 40, y: 80 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 14 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 14 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 11,
  },
  {
    id: 'ride-15',
    passengerPhone: '555-0115',
    pickup: { name: 'Lakeview Docks', coords: { x: 20, y: 95 } },
    status: 'pending',
    driverId: null,
    createdAt: new Date(now.getTime() - 15 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 15 * 60 * 1000),
    passengerCount: 2,
    movingFee: false,
    totalFare: 21,
  },

  // --- Assigned/In-Progress Rides ---
  {
    id: 'ride-16',
    passengerPhone: '555-0116',
    pickup: { name: '212 Elm St', coords: { x: 55, y: 55 } },
    dropoff: { name: '333 Birch Rd', coords: { x: 45, y: 45 } },
    status: 'assigned',
    driverId: 'driver-3',
    createdAt: new Date(now.getTime() - 10 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 2 * 60 * 1000),
    assignedAt: new Date(now.getTime() - 2 * 60 * 1000),
    passengerCount: 1,
    movingFee: true,
    stops: [{ name: 'Grocery Store', coords: { x: 50, y: 50 } }],
    totalFare: 45,
  },
  {
    id: 'ride-17',
    passengerPhone: '555-0117',
    pickup: { name: 'Themyscira', coords: { x: 15, y: 15 } },
    dropoff: { name: 'Hall of Justice', coords: { x: 90, y: 90 } },
    status: 'in-progress',
    driverId: 'driver-3',
    createdAt: new Date(now.getTime() - 15 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 5 * 60 * 1000),
    assignedAt: new Date(now.getTime() - 10 * 60 * 1000),
    pickedUpAt: new Date(now.getTime() - 5 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 80,
  },
  {
    id: 'ride-18',
    passengerPhone: '555-0118',
    pickup: { name: 'Stark Tower', coords: { x: 48, y: 52 } },
    status: 'assigned',
    driverId: 'driver-3',
    createdAt: new Date(now.getTime() - 12 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 1 * 60 * 1000),
    assignedAt: new Date(now.getTime() - 1 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 15,
  },
    {
    id: 'ride-19',
    passengerPhone: '555-0119',
    pickup: { name: 'Little Italy', coords: { x: 5, y: 88 } },
    status: 'in-progress',
    driverId: 'driver-4',
    createdAt: new Date(now.getTime() - 18 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 8 * 60 * 1000),
    assignedAt: new Date(now.getTime() - 12 * 60 * 1000),
    pickedUpAt: new Date(now.getTime() - 8 * 60 * 1000),
    passengerCount: 2,
    movingFee: false,
    totalFare: 33,
  },
    {
    id: 'ride-20',
    passengerPhone: '555-0120',
    pickup: { name: 'Greenfield Park', coords: { x: 15, y: 92 } },
    status: 'assigned',
    driverId: 'driver-4',
    createdAt: new Date(now.getTime() - 5 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 3 * 60 * 1000),
    assignedAt: new Date(now.getTime() - 3 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 24,
  },
  {
    id: 'ride-21',
    passengerPhone: '555-0121',
    pickup: { name: 'Baxter Building', coords: { x: 42, y: 58 } },
    status: 'assigned',
    driverId: 'driver-7',
    createdAt: new Date(now.getTime() - 8 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 4 * 60 * 1000),
    assignedAt: new Date(now.getTime() - 4 * 60 * 1000),
    passengerCount: 4,
    movingFee: false,
    totalFare: 29,
  },

  // --- Completed/Cancelled Rides ---
  {
    id: 'ride-22',
    passengerPhone: '555-0122',
    pickup: { name: 'Wayne Manor', coords: { x: 5, y: 5 } },
    dropoff: { name: 'Wayne Tower', coords: { x: 95, y: 5 } },
    status: 'completed',
    driverId: 'driver-1',
    createdAt: new Date(now.getTime() - 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 40 * 60 * 1000),
    assignedAt: new Date(now.getTime() - 55 * 60 * 1000),
    pickedUpAt: new Date(now.getTime() - 50 * 60 * 1000),
    droppedOffAt: new Date(now.getTime() - 40 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 85.50,
    paymentDetails: { card: 75.50, tip: 10 },
  },
  {
    id: 'ride-23',
    passengerPhone: '555-0123',
    pickup: { name: 'Daily Planet', coords: { x: 50, y: 80 } },
    status: 'cancelled',
    driverId: null,
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 110 * 60 * 1000),
    cancelledAt: new Date(now.getTime() - 110 * 60 * 1000),
    passengerCount: 1,
    movingFee: false,
    totalFare: 0,
  },
];
